language: objective-c
osx_image: xcode7.3
xcode_sdk: iphonesimulator9.3
xcode_project: RileyLink.xcodeproj
xcode_scheme: RileyLink
before_script:
    - carthage bootstrap
script:
#    - xctool -project RileyLink.xcodeproj -scheme RileyLink -sdk iphonesimulator9.3 test
