language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator10.2
xcode_project: RileyLink.xcodeproj
xcode_scheme: RileyLink
script:
    - xcodebuild -project RileyLink.xcodeproj -scheme RileyLink -sdk iphonesimulator10.2 build -destination 'id=DB794781-65A7-4884-8D00-AAC3CBD39A44' test
