language: objective-c
osx_image: xcode8
xcode_sdk: iphonesimulator10
xcode_project: RileyLink.xcodeproj
xcode_scheme: RileyLink
script:
    - xcodebuild -project RileyLink.xcodeproj -scheme RileyLink -sdk iphonesimulator10 test | xcpretty
